<?php

use App\Operacion;
use Illuminate\Database\Seeder;

class OperacionesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Operacion::insert([
            ['prmprnpre'=> '10106',	'gbagenomb'=> 'PATINO TEST YEISON',	'prmprtcre'=> '1',	'prtcrdesc'=> 'CREDITO INDIVIDUAL',	'prmprfdes'=> '41890',	'prmprmdes'=> '6990.00',	'prmprsald'=> '5824.15',	'prmprcmon'=> '1',	'moneda'=> 'BOLIVIANOS BS.',	'prmprstat'=> '2',	'estado'=> 'VIGENTE',	'prmprplzo'=> '420',	'prmprplaz'=> '70',	'plaza'=> 'SANTA CRUZ',	'prmpragen'=> '75',	'agencia'=> 'AG. COTOCA',	'prmprautp'=> '253',	'autoriza'=> 'ERWIN ORTIZ ARROYO',	'prmprrseg'=> '461',	'asesor'=> 'LEONARDO PATRICIO RODRIGUEZ RODRIGUEZ',	'ncreditos'=> '1',	'tasa'=> '36.00',	'gbagedir1'=> 'B/SAN PABLO Z/COTOCA ENTRANDO',	'cargosdesem'=> '14.40',	'cargosadmin'=> '2.50',	'prmprfpvc'=> null,	'mora'=> '0',	'gbagecage'=> '81515',	'ini_plan_pago'=> '41922',	'garantia'=> null,	'gbciidesc'=> 'SERVICIO DE TRANSPORTE AUTOMOTOR SUBURBANO DE PASAJEROS',	'ult_pago'=> '41988',	'prox_pago'=> null,	'fec_incumplimiento'=> null,	'fec_cierre'=> '42310',	'num_cuotas'=> '14',	'tipo_plazo'=> '3',	'con_mora'=> '...',	'gasto'=> '0.00',	'acbccccic'=> null,	],
            ['prmprnpre'=> '10107',	'gbagenomb'=> 'LAS TEST Y EL CLAVEL',	'prmprtcre'=> '10',	'prtcrdesc'=> 'BANCO COMUNAL',	'prmprfdes'=> '41891',	'prmprmdes'=> '29743.56',	'prmprsald'=> '11507.99',	'prmprcmon'=> '1',	'moneda'=> 'BOLIVIANOS BS.',	'prmprstat'=> '2',	'estado'=> 'VIGENTE',	'prmprplzo'=> '196',	'prmprplaz'=> '70',	'plaza'=> 'SANTA CRUZ',	'prmpragen'=> '75',	'agencia'=> 'AG. COTOCA',	'prmprautp'=> '223',	'autoriza'=> 'PABLO GARCIA',	'prmprrseg'=> '253',	'asesor'=> 'ERWIN ORTIZ ARROYO',	'ncreditos'=> '1',	'tasa'=> '36.00',	'gbagedir1'=> null,	'cargosdesem'=> '14.40',	'cargosadmin'=> '2.50',	'prmprfpvc'=> null,	'mora'=> '0',	'gbagecage'=> '77708',	'ini_plan_pago'=> '41901',	'garantia'=> null,	'gbciidesc'=> null,	'ult_pago'=> '42013',	'prox_pago'=> null,	'fec_incumplimiento'=> null,	'fec_cierre'=> '42087',	'num_cuotas'=> '14',	'tipo_plazo'=> '3',	'con_mora'=> '...',	'gasto'=> '0.00',	'acbccccic'=> '7198',	],
            ['prmprnpre'=> '10117',	'gbagenomb'=> 'AGUILAS TEST COTOCA',	'prmprtcre'=> '10',	'prtcrdesc'=> 'BANCO COMUNAL',	'prmprfdes'=> '41893',	'prmprmdes'=> '30256.38',	'prmprsald'=> '14011.52',	'prmprcmon'=> '1',	'moneda'=> 'BOLIVIANOS BS.',	'prmprstat'=> '2',	'estado'=> 'VIGENTE',	'prmprplzo'=> '196',	'prmprplaz'=> '70',	'plaza'=> 'SANTA CRUZ',	'prmpragen'=> '75',	'agencia'=> 'AG. COTOCA',	'prmprautp'=> '223',	'autoriza'=> 'PABLO GARCIA',	'prmprrseg'=> '253',	'asesor'=> 'ERWIN ORTIZ ARROYO',	'ncreditos'=> '1',	'tasa'=> '36.00',	'gbagedir1'=> null,	'cargosdesem'=> '14.40',	'cargosadmin'=> '2.50',	'prmprfpvc'=> null,	'mora'=> '0',	'gbagecage'=> '77824',	'ini_plan_pago'=> '41907',	'garantia'=> null,	'gbciidesc'=> null,	'ult_pago'=> '42006',	'prox_pago'=> null,	'fec_incumplimiento'=> null,	'fec_cierre'=> '42089',	'num_cuotas'=> '14',	'tipo_plazo'=> '3',	'con_mora'=> '...',	'gasto'=> '0.00',	'acbccccic'=> '7209',	],
            ['prmprnpre'=> '10129',	'gbagenomb'=> 'DURAN TEST MAURICIO JAVIER',	'prmprtcre'=> '1',	'prtcrdesc'=> 'CREDITO INDIVIDUAL',	'prmprfdes'=> '41894',	'prmprmdes'=> '6990.00',	'prmprsald'=> '5536.21',	'prmprcmon'=> '1',	'moneda'=> 'BOLIVIANOS BS.',	'prmprstat'=> '2',	'estado'=> 'VIGENTE',	'prmprplzo'=> '360',	'prmprplaz'=> '70',	'plaza'=> 'SANTA CRUZ',	'prmpragen'=> '75',	'agencia'=> 'AG. COTOCA',	'prmprautp'=> '253',	'autoriza'=> 'ERWIN ORTIZ ARROYO',	'prmprrseg'=> '461',	'asesor'=> 'LEONARDO PATRICIO RODRIGUEZ RODRIGUEZ',	'ncreditos'=> '1',	'tasa'=> '36.00',	'gbagedir1'=> 'C/TENIENTE ANEZ B/PARAISO Z/CO',	'cargosdesem'=> '14.40',	'cargosadmin'=> '2.50',	'prmprfpvc'=> null,	'mora'=> '0',	'gbagecage'=> '81603',	'ini_plan_pago'=> '41922',	'garantia'=> null,	'gbciidesc'=> 'SERVICIO DE EXPENDIO DE JUGOS ZUMOS Y ENSALADAS DE FRUTAS',	'ult_pago'=> '41986',	'prox_pago'=> null,	'fec_incumplimiento'=> null,	'fec_cierre'=> '42254',	'num_cuotas'=> '12',	'tipo_plazo'=> '3',	'con_mora'=> '...',	'gasto'=> '0.00',	'acbccccic'=> null,	],
            ['prmprnpre'=> '10130',	'gbagenomb'=> 'SITA TEST ALEJANDRA',	'prmprtcre'=> '1',	'prtcrdesc'=> 'CREDITO INDIVIDUAL',	'prmprfdes'=> '41898',	'prmprmdes'=> '6990.00',	'prmprsald'=> '5507.17',	'prmprcmon'=> '1',	'moneda'=> 'BOLIVIANOS BS.',	'prmprstat'=> '2',	'estado'=> 'VIGENTE',	'prmprplzo'=> '360',	'prmprplaz'=> '70',	'plaza'=> 'SANTA CRUZ',	'prmpragen'=> '75',	'agencia'=> 'AG. COTOCA',	'prmprautp'=> '253',	'autoriza'=> 'ERWIN ORTIZ ARROYO',	'prmprrseg'=> '461',	'asesor'=> 'LEONARDO PATRICIO RODRIGUEZ RODRIGUEZ',	'ncreditos'=> '1',	'tasa'=> '36.00',	'gbagedir1'=> 'B/ARBOLEDA DE FATIMA ENTRANDO',	'cargosdesem'=> '14.40',	'cargosadmin'=> '2.50',	'prmprfpvc'=> null,	'mora'=> '0',	'gbagecage'=> '81673',	'ini_plan_pago'=> '41925',	'garantia'=> null,	'gbciidesc'=> 'SERVICIO PREPARACION Y VENTA DE COMIDAS RAPIDAS',	'ult_pago'=> '41988',	'prox_pago'=> null,	'fec_incumplimiento'=> null,	'fec_cierre'=> '42258',	'num_cuotas'=> '12',	'tipo_plazo'=> '3',	'con_mora'=> '...',	'gasto'=> '0.00',	'acbccccic'=> null,	],
            ['prmprnpre'=> '10131',	'gbagenomb'=> 'SOQUERE TEST NATIVIDAD',	'prmprtcre'=> '1',	'prtcrdesc'=> 'CREDITO INDIVIDUAL',	'prmprfdes'=> '41898',	'prmprmdes'=> '4200.00',	'prmprsald'=> '3308.41',	'prmprcmon'=> '1',	'moneda'=> 'BOLIVIANOS BS.',	'prmprstat'=> '2',	'estado'=> 'VIGENTE',	'prmprplzo'=> '360',	'prmprplaz'=> '70',	'plaza'=> 'SANTA CRUZ',	'prmpragen'=> '75',	'agencia'=> 'AG. COTOCA',	'prmprautp'=> '253',	'autoriza'=> 'ERWIN ORTIZ ARROYO',	'prmprrseg'=> '461',	'asesor'=> 'LEONARDO PATRICIO RODRIGUEZ RODRIGUEZ',	'ncreditos'=> '1',	'tasa'=> '36.00',	'gbagedir1'=> 'B/SAN PABLO 2 Z/COTOCA DE LA C',	'cargosdesem'=> '14.40',	'cargosadmin'=> '2.50',	'prmprfpvc'=> null,	'mora'=> '0',	'gbagecage'=> '81670',	'ini_plan_pago'=> '41925',	'garantia'=> null,	'gbciidesc'=> 'SERVICIO PREPARACION Y VENTA DE COMIDAS RAPIDAS',	'ult_pago'=> '41988',	'prox_pago'=> null,	'fec_incumplimiento'=> null,	'fec_cierre'=> '42258',	'num_cuotas'=> '12',	'tipo_plazo'=> '3',	'con_mora'=> '...',	'gasto'=> '0.00',	'acbccccic'=> null,	],
            ['prmprnpre'=> '10132',	'gbagenomb'=> 'CHAVEZ TEST CARLA VANEZA',	'prmprtcre'=> '1',	'prtcrdesc'=> 'CREDITO INDIVIDUAL',	'prmprfdes'=> '41899',	'prmprmdes'=> '6990.00',	'prmprsald'=> '4994.11',	'prmprcmon'=> '1',	'moneda'=> 'BOLIVIANOS BS.',	'prmprstat'=> '2',	'estado'=> 'VIGENTE',	'prmprplzo'=> '360',	'prmprplaz'=> '70',	'plaza'=> 'SANTA CRUZ',	'prmpragen'=> '75',	'agencia'=> 'AG. COTOCA',	'prmprautp'=> '253',	'autoriza'=> 'ERWIN ORTIZ ARROYO',	'prmprrseg'=> '461',	'asesor'=> 'LEONARDO PATRICIO RODRIGUEZ RODRIGUEZ',	'ncreditos'=> '1',	'tasa'=> '36.00',	'gbagedir1'=> 'B/SAN PABLO DE LA CANCHA A MAN',	'cargosdesem'=> '14.40',	'cargosadmin'=> '2.50',	'prmprfpvc'=> null,	'mora'=> '0',	'gbagecage'=> '81718',	'ini_plan_pago'=> '41927',	'garantia'=> null,	'gbciidesc'=> 'SERVICIO PREPARACION Y VENTA DE COMIDAS RAPIDAS',	'ult_pago'=> '42014',	'prox_pago'=> null,	'fec_incumplimiento'=> null,	'fec_cierre'=> '42259',	'num_cuotas'=> '12',	'tipo_plazo'=> '3',	'con_mora'=> '...',	'gasto'=> '0.00',	'acbccccic'=> null,	],
            ['prmprnpre'=> '10137',	'gbagenomb'=> 'TOMICHA TEST VICENTE',	'prmprtcre'=> '1',	'prtcrdesc'=> 'CREDITO INDIVIDUAL',	'prmprfdes'=> '41905',	'prmprmdes'=> '9000.00',	'prmprsald'=> '7747.47',	'prmprcmon'=> '1',	'moneda'=> 'BOLIVIANOS BS.',	'prmprstat'=> '2',	'estado'=> 'VIGENTE',	'prmprplzo'=> '450',	'prmprplaz'=> '70',	'plaza'=> 'SANTA CRUZ',	'prmpragen'=> '75',	'agencia'=> 'AG. COTOCA',	'prmprautp'=> '223',	'autoriza'=> 'PABLO GARCIA',	'prmprrseg'=> '461',	'asesor'=> 'LEONARDO PATRICIO RODRIGUEZ RODRIGUEZ',	'ncreditos'=> '1',	'tasa'=> '36.00',	'gbagedir1'=> 'B/SAN PABLO 2 Z/COTOCA PASANDO',	'cargosdesem'=> '14.40',	'cargosadmin'=> '2.50',	'prmprfpvc'=> null,	'mora'=> '0',	'gbagecage'=> '81850',	'ini_plan_pago'=> '41947',	'garantia'=> null,	'gbciidesc'=> 'SERVICIO DE TRANSPORTE AUTOMOTOR SUBURBANO DE PASAJEROS',	'ult_pago'=> '42009',	'prox_pago'=> null,	'fec_incumplimiento'=> null,	'fec_cierre'=> '42355',	'num_cuotas'=> '15',	'tipo_plazo'=> '3',	'con_mora'=> '...',	'gasto'=> '0.00',	'acbccccic'=> null,	],
            ['prmprnpre'=> '22029306',	'gbagenomb'=> 'PATTY TEST LUCIO',	'prmprtcre'=> '52',	'prtcrdesc'=> 'CREDITO INDIVIDUAL REPROGRAMADO',	'prmprfdes'=> '40842',	'prmprmdes'=> '10000.00',	'prmprsald'=> '5876.14',	'prmprcmon'=> '2',	'moneda'=> 'DOLARES$US.',	'prmprstat'=> '2',	'estado'=> 'VIGENTE',	'prmprplzo'=> '2309',	'prmprplaz'=> '20',	'plaza'=> 'LA PAZ',	'prmpragen'=> '28',	'agencia'=> 'AG. BATALLAS',	'prmprautp'=> '1001',	'autoriza'=> 'RAMIRO QUISPE',	'prmprrseg'=> '279',	'asesor'=> 'SANTIAGO TOMAS CORONEL GUACHALLA',	'ncreditos'=> '2',	'tasa'=> '24.00',	'gbagedir1'=> 'CALLE LITORAL S/N COMUNIDAD CH',	'cargosdesem'=> '0.00',	'cargosadmin'=> '1.00',	'prmprfpvc'=> null,	'mora'=> '0',	'gbagecage'=> '57545',	'ini_plan_pago'=> '40882',	'garantia'=> '',	'gbciidesc'=> 'OTROS SERVICIOS DE TRANSPORTE NO REGULAR DE PASAJEROS',	'ult_pago'=> '42087',	'prox_pago'=> null,	'fec_incumplimiento'=> null,	'fec_cierre'=> '43151',	'num_cuotas'=> '75',	'tipo_plazo'=> '3',	'con_mora'=> '...',	'gasto'=> '0.00',	'acbccccic'=> null,	],
        ]);

        Operacion::insert([
            ['prmprnpre'=> '22029808',	'gbagenomb'=> 'MAMANI TEST ROBERTO RODOLFO',	'prmprtcre'=> '1',	'prtcrdesc'=> 'CREDITO INDIVIDUAL',	'prmprfdes'=> '40887',	'prmprmdes'=> '10000.00',	'prmprsald'=> '3463.33',	'prmprcmon'=> '2',	'moneda'=> 'DOLARES$US.',	'prmprstat'=> '2',	'estado'=> 'VIGENTE',	'prmprplzo'=> '1440',	'prmprplaz'=> '20',	'plaza'=> 'LA PAZ',	'prmpragen'=> '22',	'agencia'=> 'AG. 16 DE JULIO',	'prmprautp'=> '1001',	'autoriza'=> 'RAMIRO QUISPE',	'prmprrseg'=> '287',	'asesor'=> 'LEDY LAURA CUIZA ORIHUELA',	'ncreditos'=> '1',	'tasa'=> '24.00',	'gbagedir1'=> 'PLAZA BOLIVIA CAMBIA # 2224 ZO',	'cargosdesem'=> '0.00',	'cargosadmin'=> '1.00',	'prmprfpvc'=> '41922',	'mora'=> '94',	'gbagecage'=> '8452',	'ini_plan_pago'=> '40918',	'garantia'=> ' HIPOTECA CON FOLIO REAL 2.01.4.0011417',	'gbciidesc'=> 'SERVICIO DE TRANSPORTE AUTOMOTOR URBANO DE PASAJEROS',	'ult_pago'=> '41997',	'prox_pago'=> '41922',	'fec_incumplimiento'=> '41922',	'fec_cierre'=> '42327',	'num_cuotas'=> '48',	'tipo_plazo'=> '3',	'con_mora'=> '...',	'gasto'=> '0.00',	'acbccccic'=> null,	],
            ['prmprnpre'=> '22030324',	'gbagenomb'=> 'VARGAS TEST DORA',	'prmprtcre'=> '1',	'prtcrdesc'=> 'CREDITO INDIVIDUAL',	'prmprfdes'=> '40938',	'prmprmdes'=> '4500.00',	'prmprsald'=> '354.93',	'prmprcmon'=> '2',	'moneda'=> 'DOLARES$US.',	'prmprstat'=> '2',	'estado'=> 'VIGENTE',	'prmprplzo'=> '1080',	'prmprplaz'=> '20',	'plaza'=> 'LA PAZ',	'prmpragen'=> '22',	'agencia'=> 'AG. 16 DE JULIO',	'prmprautp'=> '111',	'autoriza'=> 'CINTIA TROCHE',	'prmprrseg'=> '104',	'asesor'=> 'MARIA ESTHER ALVAREZ',	'ncreditos'=> '1',	'tasa'=> '26.00',	'gbagedir1'=> 'AVENIDA ALFONZO UGARTE N? 133',	'cargosdesem'=> '0.00',	'cargosadmin'=> '1.00',	'prmprfpvc'=> '41922',	'mora'=> '94',	'gbagecage'=> '5850',	'ini_plan_pago'=> '40980',	'garantia'=> null,	'gbciidesc'=> 'VENTA AL POR MAYOR DE OTROS PRODUCTOS',	'ult_pago'=> '42004',	'prox_pago'=> '41922',	'fec_incumplimiento'=> '41922',	'fec_cierre'=> '42018',	'num_cuotas'=> '36',	'tipo_plazo'=> '3',	'con_mora'=> '...',	'gasto'=> '0.00',	'acbccccic'=> null,	],
            ['prmprnpre'=> '22031293',	'gbagenomb'=> 'MANCILLA TEST MARCO ANTONIO',	'prmprtcre'=> '1',	'prtcrdesc'=> 'CREDITO INDIVIDUAL',	'prmprfdes'=> '41015',	'prmprmdes'=> '4500.00',	'prmprsald'=> '694.78',	'prmprcmon'=> '2',	'moneda'=> 'DOLARES$US.',	'prmprstat'=> '2',	'estado'=> 'VIGENTE',	'prmprplzo'=> '1080',	'prmprplaz'=> '20',	'plaza'=> 'LA PAZ',	'prmpragen'=> '22',	'agencia'=> 'AG. 16 DE JULIO',	'prmprautp'=> '1001',	'autoriza'=> 'RAMIRO QUISPE',	'prmprrseg'=> '287',	'asesor'=> 'LEDY LAURA CUIZA ORIHUELA',	'ncreditos'=> '1',	'tasa'=> '26.00',	'gbagedir1'=> 'CALLE ROSENDO ROJAS NRO.374 VI',	'cargosdesem'=> '0.00',	'cargosadmin'=> '1.00',	'prmprfpvc'=> null,	'mora'=> '0',	'gbagecage'=> '61340',	'ini_plan_pago'=> '41044',	'garantia'=> null,	'gbciidesc'=> 'VENTA AL POR MAYOR DE OTROS PRODUCTOS',	'ult_pago'=> '41991',	'prox_pago'=> null,	'fec_incumplimiento'=> null,	'fec_cierre'=> '42095',	'num_cuotas'=> '36',	'tipo_plazo'=> '3',	'con_mora'=> '...',	'gasto'=> '0.00',	'acbccccic'=> null,	],
            ['prmprnpre'=> '22031452',	'gbagenomb'=> 'CAZAS TEST ALBERTO',	'prmprtcre'=> '1',	'prtcrdesc'=> 'CREDITO INDIVIDUAL',	'prmprfdes'=> '41027',	'prmprmdes'=> '4500.00',	'prmprsald'=> '697.76',	'prmprcmon'=> '2',	'moneda'=> 'DOLARES$US.',	'prmprstat'=> '2',	'estado'=> 'VIGENTE',	'prmprplzo'=> '1080',	'prmprplaz'=> '20',	'plaza'=> 'LA PAZ',	'prmpragen'=> '22',	'agencia'=> 'AG. 16 DE JULIO',	'prmprautp'=> '1001',	'autoriza'=> 'RAMIRO QUISPE',	'prmprrseg'=> '287',	'asesor'=> 'LEDY LAURA CUIZA ORIHUELA',	'ncreditos'=> '2',	'tasa'=> '26.00',	'gbagedir1'=> 'CALLE 16 DE AGOSTO NO. 4515 ZO',	'cargosdesem'=> '0.00',	'cargosadmin'=> '1.00',	'prmprfpvc'=> null,	'mora'=> '0',	'gbagecage'=> '57161',	'ini_plan_pago'=> '41071',	'garantia'=> null,	'gbciidesc'=> 'OTROS SERVICIOS DE EXPENDIO DE COMIDAS NCP.',	'ult_pago'=> '42016',	'prox_pago'=> null,	'fec_incumplimiento'=> null,	'fec_cierre'=> '42107',	'num_cuotas'=> '36',	'tipo_plazo'=> '3',	'con_mora'=> '...',	'gasto'=> '0.00',	'acbccccic'=> null,	],
            ['prmprnpre'=> '22031854',	'gbagenomb'=> 'CONDORI TEST RAUL',	'prmprtcre'=> '1',	'prtcrdesc'=> 'CREDITO INDIVIDUAL',	'prmprfdes'=> '41076',	'prmprmdes'=> '22000.00',	'prmprsald'=> '5839.05',	'prmprcmon'=> '1',	'moneda'=> 'BOLIVIANOS BS.',	'prmprstat'=> '2',	'estado'=> 'VIGENTE',	'prmprplzo'=> '1080',	'prmprplaz'=> '20',	'plaza'=> 'LA PAZ',	'prmpragen'=> '22',	'agencia'=> 'AG. 16 DE JULIO',	'prmprautp'=> '1001',	'autoriza'=> 'RAMIRO QUISPE',	'prmprrseg'=> '287',	'asesor'=> 'LEDY LAURA CUIZA ORIHUELA',	'ncreditos'=> '1',	'tasa'=> '33.00',	'gbagedir1'=> 'AV. ARGENTINA# 7482URB. SR',	'cargosdesem'=> '9.00',	'cargosadmin'=> '2.50',	'prmprfpvc'=> null,	'mora'=> '0',	'gbagecage'=> '60782',	'ini_plan_pago'=> '41106',	'garantia'=> null,	'gbciidesc'=> 'FABRICACION DE CHOMPAS Y ARTICULOS SIMILARES DE PUNTO',	'ult_pago'=> '41995',	'prox_pago'=> null,	'fec_incumplimiento'=> null,	'fec_cierre'=> '42156',	'num_cuotas'=> '36',	'tipo_plazo'=> '3',	'con_mora'=> '...',	'gasto'=> '0.00',	'acbccccic'=> null,	],
        ]);

        Operacion::insert([
            ['prmprnpre'=> '22032576',	'gbagenomb'=> 'CABAS TEST HILDA VIRGINIA',	'prmprtcre'=> '1',	'prtcrdesc'=> 'CREDITO INDIVIDUAL',	'prmprfdes'=> '41137',	'prmprmdes'=> '1205.91',	'prmprsald'=> '129.40',	'prmprcmon'=> '2',	'moneda'=> 'DOLARES$US.',	'prmprstat'=> '2',	'estado'=> 'VIGENTE',	'prmprplzo'=> '900',	'prmprplaz'=> '20',	'plaza'=> 'LA PAZ',	'prmpragen'=> '22',	'agencia'=> 'AG. 16 DE JULIO',	'prmprautp'=> '117',	'autoriza'=> 'JOSE LUIS VILLARROEL',	'prmprrseg'=> '287',	'asesor'=> 'LEDY LAURA CUIZA ORIHUELA',	'ncreditos'=> '1',	'tasa'=> '36.00',	'gbagedir1'=> 'CALLE RIVAS N? 2227',	'cargosdesem'=> '10.20',	'cargosadmin'=> '0.00',	'prmprfpvc'=> '41922',	'mora'=> '94',	'gbagecage'=> '8538',	'ini_plan_pago'=> '41162',	'garantia'=> null,	'gbciidesc'=> 'VENTA AL POR MENORDE PRODUCTOS TEXTILES EXCEPTO PRENDAS DE VESTIR',	'ult_pago'=> '41997',	'prox_pago'=> '41922',	'fec_incumplimiento'=> '41922',	'fec_cierre'=> '42037',	'num_cuotas'=> '30',	'tipo_plazo'=> '3',	'con_mora'=> '...',	'gasto'=> '0.00',	'acbccccic'=> null,	],
            ['prmprnpre'=> '22032749',	'gbagenomb'=> 'PINEL TEST FLORENCIA',	'prmprtcre'=> '1',	'prtcrdesc'=> 'CREDITO INDIVIDUAL',	'prmprfdes'=> '41150',	'prmprmdes'=> '3500.00',	'prmprsald'=> '996.36',	'prmprcmon'=> '2',	'moneda'=> 'DOLARES$US.',	'prmprstat'=> '2',	'estado'=> 'VIGENTE',	'prmprplzo'=> '1080',	'prmprplaz'=> '20',	'plaza'=> 'LA PAZ',	'prmpragen'=> '22',	'agencia'=> 'AG. 16 DE JULIO',	'prmprautp'=> '117',	'autoriza'=> 'JOSE LUIS VILLARROEL',	'prmprrseg'=> '287',	'asesor'=> 'LEDY LAURA CUIZA ORIHUELA',	'ncreditos'=> '1',	'tasa'=> '30.00',	'gbagedir1'=> 'CALLE FRANCISCO ROMERO N? 50 Z',	'cargosdesem'=> '6.00',	'cargosadmin'=> '1.50',	'prmprfpvc'=> null,	'mora'=> '0',	'gbagecage'=> '64589',	'ini_plan_pago'=> '41169',	'garantia'=> null,	'gbciidesc'=> 'VENTA AL POR MENOR DE OTROS PRODUCTOS EN ALMACENES NO ESPECIALIZADOS',	'ult_pago'=> '41988',	'prox_pago'=> null,	'fec_incumplimiento'=> null,	'fec_cierre'=> '42230',	'num_cuotas'=> '36',	'tipo_plazo'=> '3',	'con_mora'=> '...',	'gasto'=> '0.00',	'acbccccic'=> null,	],
            ['prmprnpre'=> '22033130',	'gbagenomb'=> 'CARVAJAL TEST ANCELMO',	'prmprtcre'=> '1',	'prtcrdesc'=> 'CREDITO INDIVIDUAL',	'prmprfdes'=> '41173',	'prmprmdes'=> '10000.00',	'prmprsald'=> '4978.90',	'prmprcmon'=> '2',	'moneda'=> 'DOLARES$US.',	'prmprstat'=> '2',	'estado'=> 'VIGENTE',	'prmprplzo'=> '1440',	'prmprplaz'=> '20',	'plaza'=> 'LA PAZ',	'prmpragen'=> '28',	'agencia'=> 'AG. BATALLAS',	'prmprautp'=> '111',	'autoriza'=> 'CINTIA TROCHE',	'prmprrseg'=> '279',	'asesor'=> 'SANTIAGO TOMAS CORONEL GUACHALLA',	'ncreditos'=> '1',	'tasa'=> '24.00',	'gbagedir1'=> 'CORAPATA LOS ANDES S/N ZONA HU',	'cargosdesem'=> '0.00',	'cargosadmin'=> '1.00',	'prmprfpvc'=> null,	'mora'=> '0',	'gbagecage'=> '65195',	'ini_plan_pago'=> '41218',	'garantia'=> 'HIPOTECA CON NUMERO DE FOLIO 2.01.4.0051192',	'gbciidesc'=> 'VENTA AL POR MAYOR DE OTROS PRODUCTOS',	'ult_pago'=> '42100',	'prox_pago'=> null,	'fec_incumplimiento'=> null,	'fec_cierre'=> '42613',	'num_cuotas'=> '48',	'tipo_plazo'=> '3',	'con_mora'=> '...',	'gasto'=> '0.00',	'acbccccic'=> null,	],
            ['prmprnpre'=> '22033199',	'gbagenomb'=> 'QUISPE TEST JUANA SUXO DE',	'prmprtcre'=> '1',	'prtcrdesc'=> 'CREDITO INDIVIDUAL',	'prmprfdes'=> '41177',	'prmprmdes'=> '2500.00',	'prmprsald'=> '505.99',	'prmprcmon'=> '2',	'moneda'=> 'DOLARES$US.',	'prmprstat'=> '5',	'estado'=> 'VENCIDO',	'prmprplzo'=> '720',	'prmprplaz'=> '20',	'plaza'=> 'LA PAZ',	'prmpragen'=> '22',	'agencia'=> 'AG. 16 DE JULIO',	'prmprautp'=> '117',	'autoriza'=> 'JOSE LUIS VILLARROEL',	'prmprrseg'=> '104',	'asesor'=> 'MARIA ESTHER ALVAREZ',	'ncreditos'=> '1',	'tasa'=> '33.00',	'gbagedir1'=> 'CALLE PASCUA 507',	'cargosdesem'=> '9.00',	'cargosadmin'=> '2.50',	'prmprfpvc'=> '41826',	'mora'=> '190',	'gbagecage'=> '9004',	'ini_plan_pago'=> '41219',	'garantia'=> null,	'gbciidesc'=> 'VENTA AL POR MENOR DE OTROS PRODUCTOS EN ALMACENES ESPECIALIZADOS NCP',	'ult_pago'=> '41759',	'prox_pago'=> '41826',	'fec_incumplimiento'=> '41826',	'fec_cierre'=> '41897',	'num_cuotas'=> '24',	'tipo_plazo'=> '3',	'con_mora'=> '...',	'gasto'=> '0.00',	'acbccccic'=> null,	],
            ['prmprnpre'=> '22033309',	'gbagenomb'=> 'BELTRAN TEST',	'prmprtcre'=> '1',	'prtcrdesc'=> 'CREDITO INDIVIDUAL',	'prmprfdes'=> '41181',	'prmprmdes'=> '5500.00',	'prmprsald'=> '3218.41',	'prmprcmon'=> '2',	'moneda'=> 'DOLARES$US.',	'prmprstat'=> '2',	'estado'=> 'VIGENTE',	'prmprplzo'=> '1440',	'prmprplaz'=> '20',	'plaza'=> 'LA PAZ',	'prmpragen'=> '22',	'agencia'=> 'AG. 16 DE JULIO',	'prmprautp'=> '117',	'autoriza'=> 'JOSE LUIS VILLARROEL',	'prmprrseg'=> '425',	'asesor'=> 'MAGALY SOTO PORTUGAL',	'ncreditos'=> '1',	'tasa'=> '24.00',	'gbagedir1'=> 'URB.LOS ALAMOS AV.6 DE MARZO N',	'cargosdesem'=> '0.00',	'cargosadmin'=> '1.00',	'prmprfpvc'=> null,	'mora'=> '0',	'gbagecage'=> '65465',	'ini_plan_pago'=> '41225',	'garantia'=> null,	'gbciidesc'=> 'VENTA AL POR MAYOR DE OTROS PRODUCTOS',	'ult_pago'=> '41988',	'prox_pago'=> null,	'fec_incumplimiento'=> null,	'fec_cierre'=> '42621',	'num_cuotas'=> '48',	'tipo_plazo'=> '3',	'con_mora'=> '...',	'gasto'=> '0.00',	'acbccccic'=> null,	],
            ['prmprnpre'=> '22034512',	'gbagenomb'=> 'ALANOCA TEST EDDY FREDDY',	'prmprtcre'=> '1',	'prtcrdesc'=> 'CREDITO INDIVIDUAL',	'prmprfdes'=> '41239',	'prmprmdes'=> '1500.00',	'prmprsald'=> '99.51',	'prmprcmon'=> '2',	'moneda'=> 'DOLARES$US.',	'prmprstat'=> '5',	'estado'=> 'VENCIDO',	'prmprplzo'=> '720',	'prmprplaz'=> '20',	'plaza'=> 'LA PAZ',	'prmpragen'=> '22',	'agencia'=> 'AG. 16 DE JULIO',	'prmprautp'=> '104',	'autoriza'=> 'MARIA ESTHER ALVAREZ',	'prmprrseg'=> '104',	'asesor'=> 'MARIA ESTHER ALVAREZ',	'ncreditos'=> '1',	'tasa'=> '36.00',	'gbagedir1'=> 'CALLE HILATA N.2075 ZONA 25 DE',	'cargosdesem'=> '10.20',	'cargosadmin'=> '2.50',	'prmprfpvc'=> '41976',	'mora'=> '40',	'gbagecage'=> '66950',	'ini_plan_pago'=> '41276',	'garantia'=> null,	'gbciidesc'=> 'VENTA AL POR MAYOR DE OTROS PRODUCTOS',	'ult_pago'=> '41975',	'prox_pago'=> '41976',	'fec_incumplimiento'=> '41976',	'fec_cierre'=> '41959',	'num_cuotas'=> '24',	'tipo_plazo'=> '3',	'con_mora'=> '...',	'gasto'=> '0.00',	'acbccccic'=> null,	],
        ]);

        Operacion::insert([
            ['prmprnpre'=> '22035250',	'gbagenomb'=> 'MAMANI TEST SILVIA EUGENIA',	'prmprtcre'=> '1',	'prtcrdesc'=> 'CREDITO INDIVIDUAL',	'prmprfdes'=> '41278',	'prmprmdes'=> '17500.00',	'prmprsald'=> '1092.41',	'prmprcmon'=> '1',	'moneda'=> 'BOLIVIANOS BS.',	'prmprstat'=> '2',	'estado'=> 'VIGENTE',	'prmprplzo'=> '720',	'prmprplaz'=> '20',	'plaza'=> 'LA PAZ',	'prmpragen'=> '22',	'agencia'=> 'AG. 16 DE JULIO',	'prmprautp'=> '104',	'autoriza'=> 'MARIA ESTHER ALVAREZ',	'prmprrseg'=> '287',	'asesor'=> 'LEDY LAURA CUIZA ORIHUELA',	'ncreditos'=> '1',	'tasa'=> '36.00',	'gbagedir1'=> 'CALLE 18 N 525',	'cargosdesem'=> '9.00',	'cargosadmin'=> '2.50',	'prmprfpvc'=> '41922',	'mora'=> '94',	'gbagecage'=> '7892',	'ini_plan_pago'=> '41316',	'garantia'=> null,	'gbciidesc'=> 'VENTA AL POR MAYOR DE OTROS PRODUCTOS',	'ult_pago'=> '42003',	'prox_pago'=> '41922',	'fec_incumplimiento'=> '41922',	'fec_cierre'=> '41998',	'num_cuotas'=> '24',	'tipo_plazo'=> '3',	'con_mora'=> '...',	'gasto'=> '0.00',	'acbccccic'=> null,	],
            ['prmprnpre'=> '22035506',	'gbagenomb'=> 'ULO TEST PRUDENCIA',	'prmprtcre'=> '1',	'prtcrdesc'=> 'CREDITO INDIVIDUAL',	'prmprfdes'=> '41291',	'prmprmdes'=> '2000.00',	'prmprsald'=> '124.02',	'prmprcmon'=> '2',	'moneda'=> 'DOLARES$US.',	'prmprstat'=> '2',	'estado'=> 'VIGENTE',	'prmprplzo'=> '720',	'prmprplaz'=> '20',	'plaza'=> 'LA PAZ',	'prmpragen'=> '22',	'agencia'=> 'AG. 16 DE JULIO',	'prmprautp'=> '104',	'autoriza'=> 'MARIA ESTHER ALVAREZ',	'prmprrseg'=> '287',	'asesor'=> 'LEDY LAURA CUIZA ORIHUELA',	'ncreditos'=> '1',	'tasa'=> '36.00',	'gbagedir1'=> 'AV. VENANCIO CONDORI# 1014',	'cargosdesem'=> '10.20',	'cargosadmin'=> '2.50',	'prmprfpvc'=> '41920',	'mora'=> '96',	'gbagecage'=> '60444',	'ini_plan_pago'=> '41320',	'garantia'=> null,	'gbciidesc'=> 'FABRICACION DE OTROS PRODUCTOS TEXTILES NCP',	'ult_pago'=> '42003',	'prox_pago'=> '41920',	'fec_incumplimiento'=> '41920',	'fec_cierre'=> '42011',	'num_cuotas'=> '24',	'tipo_plazo'=> '3',	'con_mora'=> '...',	'gasto'=> '0.00',	'acbccccic'=> null,	],
            ['prmprnpre'=> '22035507',	'gbagenomb'=> 'CHOQUE TESTMAURICIO DE',	'prmprtcre'=> '1',	'prtcrdesc'=> 'CREDITO INDIVIDUAL',	'prmprfdes'=> '41292',	'prmprmdes'=> '2500.00',	'prmprsald'=> '149.69',	'prmprcmon'=> '2',	'moneda'=> 'DOLARES$US.',	'prmprstat'=> '2',	'estado'=> 'VIGENTE',	'prmprplzo'=> '720',	'prmprplaz'=> '20',	'plaza'=> 'LA PAZ',	'prmpragen'=> '22',	'agencia'=> 'AG. 16 DE JULIO',	'prmprautp'=> '104',	'autoriza'=> 'MARIA ESTHER ALVAREZ',	'prmprrseg'=> '287',	'asesor'=> 'LEDY LAURA CUIZA ORIHUELA',	'ncreditos'=> '1',	'tasa'=> '33.00',	'gbagedir1'=> 'C/2#695',	'cargosdesem'=> '9.00',	'cargosadmin'=> '2.50',	'prmprfpvc'=> '41922',	'mora'=> '94',	'gbagecage'=> '54167',	'ini_plan_pago'=> '41316',	'garantia'=> null,	'gbciidesc'=> 'VENTA AL POR MENOR DE PRENDAS Y ACCESORIOS DE VESTIR',	'ult_pago'=> '41988',	'prox_pago'=> '41922',	'fec_incumplimiento'=> '41922',	'fec_cierre'=> '42012',	'num_cuotas'=> '24',	'tipo_plazo'=> '3',	'con_mora'=> '...',	'gasto'=> '0.00',	'acbccccic'=> null,	],
            ['prmprnpre'=> '22035719',	'gbagenomb'=> 'MAYTA TEST ROSALIA',	'prmprtcre'=> '1',	'prtcrdesc'=> 'CREDITO INDIVIDUAL',	'prmprfdes'=> '41303',	'prmprmdes'=> '12000.00',	'prmprsald'=> '1534.91',	'prmprcmon'=> '1',	'moneda'=> 'BOLIVIANOS BS.',	'prmprstat'=> '2',	'estado'=> 'VIGENTE',	'prmprplzo'=> '720',	'prmprplaz'=> '20',	'plaza'=> 'LA PAZ',	'prmpragen'=> '22',	'agencia'=> 'AG. 16 DE JULIO',	'prmprautp'=> '104',	'autoriza'=> 'MARIA ESTHER ALVAREZ',	'prmprrseg'=> '425',	'asesor'=> 'MAGALY SOTO PORTUGAL',	'ncreditos'=> '1',	'tasa'=> '36.00',	'gbagedir1'=> 'CALLE CHOCAYAN?2225',	'cargosdesem'=> '14.40',	'cargosadmin'=> '2.50',	'prmprfpvc'=> '41918',	'mora'=> '98',	'gbagecage'=> '9366',	'ini_plan_pago'=> '41338',	'garantia'=> null,	'gbciidesc'=> 'VENTA AL POR MAYOR DE OTROS PRODUCTOS',	'ult_pago'=> '41990',	'prox_pago'=> '41918',	'fec_incumplimiento'=> '41918',	'fec_cierre'=> '42023',	'num_cuotas'=> '24',	'tipo_plazo'=> '3',	'con_mora'=> '...',	'gasto'=> '0.00',	'acbccccic'=> null,	],
            ['prmprnpre'=> '22035721',	'gbagenomb'=> 'LAURA TEST MARINO',	'prmprtcre'=> '52',	'prtcrdesc'=> 'CREDITO INDIVIDUAL REPROGRAMADO',	'prmprfdes'=> '41303',	'prmprmdes'=> '15000.00',	'prmprsald'=> '11148.83',	'prmprcmon'=> '2',	'moneda'=> 'DOLARES$US.',	'prmprstat'=> '2',	'estado'=> 'VIGENTE',	'prmprplzo'=> '2806',	'prmprplaz'=> '20',	'plaza'=> 'LA PAZ',	'prmpragen'=> '22',	'agencia'=> 'AG. 16 DE JULIO',	'prmprautp'=> '1001',	'autoriza'=> 'RAMIRO QUISPE',	'prmprrseg'=> '287',	'asesor'=> 'LEDY LAURA CUIZA ORIHUELA',	'ncreditos'=> '1',	'tasa'=> '24.00',	'gbagedir1'=> 'AV.27 DE MAYO N.2195 ZONA URB.',	'cargosdesem'=> '0.00',	'cargosadmin'=> '1.00',	'prmprfpvc'=> '41922',	'mora'=> '94',	'gbagecage'=> '68967',	'ini_plan_pago'=> '41344',	'garantia'=> 'HIPOTECA CON FOLIO REAL 2.01.4.01.0166168',	'gbciidesc'=> 'VENTA AL POR MAYOR DE OTROS PRODUCTOS',	'ult_pago'=> '42009',	'prox_pago'=> '41922',	'fec_incumplimiento'=> '41922',	'fec_cierre'=> '44109',	'num_cuotas'=> '92',	'tipo_plazo'=> '3',	'con_mora'=> '...',	'gasto'=> '0.00',	'acbccccic'=> null,	],
            ['prmprnpre'=> '22036008',	'gbagenomb'=> 'MITA TEST QUISPE FELIPA',	'prmprtcre'=> '1',	'prtcrdesc'=> 'CREDITO INDIVIDUAL',	'prmprfdes'=> '41314',	'prmprmdes'=> '10000.00',	'prmprsald'=> '649.83',	'prmprcmon'=> '1',	'moneda'=> 'BOLIVIANOS BS.',	'prmprstat'=> '2',	'estado'=> 'VIGENTE',	'prmprplzo'=> '720',	'prmprplaz'=> '20',	'plaza'=> 'LA PAZ',	'prmpragen'=> '22',	'agencia'=> 'AG. 16 DE JULIO',	'prmprautp'=> '104',	'autoriza'=> 'MARIA ESTHER ALVAREZ',	'prmprrseg'=> '287',	'asesor'=> 'LEDY LAURA CUIZA ORIHUELA',	'ncreditos'=> '2',	'tasa'=> '36.00',	'gbagedir1'=> 'CALLE 5 NO. 42 ZONA VILLA TUNA',	'cargosdesem'=> '14.40',	'cargosadmin'=> '2.50',	'prmprfpvc'=> null,	'mora'=> '0',	'gbagecage'=> '5482',	'ini_plan_pago'=> '41344',	'garantia'=> null,	'gbciidesc'=> 'VENTA AL POR MAYOR DE OTROS PRODUCTOS',	'ult_pago'=> '42016',	'prox_pago'=> null,	'fec_incumplimiento'=> null,	'fec_cierre'=> '42034',	'num_cuotas'=> '24',	'tipo_plazo'=> '3',	'con_mora'=> '...',	'gasto'=> '0.00',	'acbccccic'=> null,	],
        ]);
    }
}
