name: Diaconia

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: composer install --no-ansi --no-interaction
      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache
      - name: Setup Redis
        uses: zhulik/redis-action@1.1.0
      - name: Install application
        run: |
          php artisan app:config --no-interaction
          php artisan app:install
          php artisan cache:clear
      - name: Install frontend
        run: |
          npm install
          npm run prod
          npm install laravel-echo-server
      - name: Execute tests (Unit and Feature tests) via PHPUnit
        run: vendor/bin/phpunit
      - name: Start laravel echo in the background
        run: node node_modules/laravel-echo-server/bin/server.js start &
      - name: Cypress run
        uses: cypress-io/github-action@v1
        with:
          start: php artisan serve
          # quote the url to be safe against YML parsing surprises
          wait-on: "http://localhost:8000"
          # the entire command will automatically be prefixed with "npm"
          # and we need the second "npm" to execute "cypress run ..." command line
          command: npm run cy:run
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: cypress execution
          path: cypress/
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: logs
          path: storage/logs/
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: coverage
          path: coverage/
